// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
    tenant_id, user_id, request_id, action, 
    resource_type, resource_id, before_state, after_state, 
    reason_code, ip_address
) VALUES (
    $1, $2, $3, $4, 
    $5, $6, $7, $8, 
    $9, $10
) RETURNING id, tenant_id, user_id, request_id, action, resource_type, resource_id, before_state, after_state, reason_code, ip_address, created_at
`

type CreateAuditLogParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
	RequestID    pgtype.Text `json:"request_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	BeforeState  []byte      `json:"before_state"`
	AfterState   []byte      `json:"after_state"`
	ReasonCode   pgtype.Text `json:"reason_code"`
	IpAddress    pgtype.Text `json:"ip_address"`
}

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.UserID,
		arg.RequestID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeState,
		arg.AfterState,
		arg.ReasonCode,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RequestID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.BeforeState,
		&i.AfterState,
		&i.ReasonCode,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}
