// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// auth_queries.go - Manual queries for authentication (not generated by sqlc)

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// AuthUser represents a user for authentication
type AuthUser struct {
	ID       pgtype.UUID
	Email    pgtype.Text
	FullName string
	IsActive pgtype.Bool
}

// AuthIdentity represents a user's authentication identity (renamed to avoid sqlc conflict)
type AuthIdentity struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Provider   string
	Identifier string
	Credential pgtype.Text
}

// UserRoleAssignment represents a user's role assignment
type UserRoleAssignment struct {
	RoleCode string
	TenantID pgtype.UUID
}


// GetUserByEmail retrieves a user by their email address
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	const query = `SELECT id, email, full_name, is_active FROM users WHERE email = $1`
	
	row := q.db.QueryRow(ctx, query, email)
	var user AuthUser
	err := row.Scan(&user.ID, &user.Email, &user.FullName, &user.IsActive)
	return user, err
}

// GetUserIdentityParams are the params for GetUserIdentity
type GetUserIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
}

// GetUserIdentity retrieves a user's identity for a specific provider
func (q *Queries) GetUserIdentity(ctx context.Context, arg GetUserIdentityParams) (AuthIdentity, error) {
	const query = `SELECT id, user_id, provider, identifier, credential 
	               FROM user_identities 
	               WHERE user_id = $1 AND provider = $2`
	
	row := q.db.QueryRow(ctx, query, arg.UserID, arg.Provider)
	var identity AuthIdentity
	err := row.Scan(&identity.ID, &identity.UserID, &identity.Provider, 
		&identity.Identifier, &identity.Credential)
	return identity, err
}


// GetUserRoleAssignmentRow is the return type for GetUserRoleAssignment
type GetUserRoleAssignmentRow struct {
	RoleCode string
	TenantID pgtype.UUID
}

// GetUserRoleAssignment retrieves a user's primary role assignment
func (q *Queries) GetUserRoleAssignment(ctx context.Context, userID pgtype.UUID) (GetUserRoleAssignmentRow, error) {
	const query = `SELECT r.code, ra.tenant_id
	               FROM role_assignments ra
	               JOIN roles r ON r.id = ra.role_id
	               WHERE ra.user_id = $1
	               LIMIT 1`
	
	row := q.db.QueryRow(ctx, query, userID)
	var result GetUserRoleAssignmentRow
	err := row.Scan(&result.RoleCode, &result.TenantID)
	if err == pgx.ErrNoRows {
		return GetUserRoleAssignmentRow{RoleCode: "guest"}, nil
	}
	return result, err
}

// UpdateUserLastLoginParams are the params for UpdateUserLastLogin
type UpdateUserLastLoginParams struct {
	ID       pgtype.UUID
	Provider string
}

// UpdateUserLastLogin updates the last_login timestamp for a user identity
func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	const query = `UPDATE user_identities SET last_login = NOW() WHERE id = $1`
	_, err := q.db.Exec(ctx, query, arg.ID)
	return err
}
