// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchUpsertAttendanceEntries implements pgx.CopyFromSource.
type iteratorForBatchUpsertAttendanceEntries struct {
	rows                 []BatchUpsertAttendanceEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchUpsertAttendanceEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchUpsertAttendanceEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SessionID,
		r.rows[0].StudentID,
		r.rows[0].Status,
		r.rows[0].Remarks,
	}, nil
}

func (r iteratorForBatchUpsertAttendanceEntries) Err() error {
	return nil
}

func (q *Queries) BatchUpsertAttendanceEntries(ctx context.Context, arg []BatchUpsertAttendanceEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attendance_entries"}, []string{"session_id", "student_id", "status", "remarks"}, &iteratorForBatchUpsertAttendanceEntries{rows: arg})
}
