// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: files_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    tenant_id, bucket, key, name, mime_type, size, uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, bucket, key, name, mime_type, size, url, uploaded_by, created_at, updated_at
`

type CreateFileParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Bucket     string      `json:"bucket"`
	Key        string      `json:"key"`
	Name       string      `json:"name"`
	MimeType   pgtype.Text `json:"mime_type"`
	Size       pgtype.Int8 `json:"size"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.TenantID,
		arg.Bucket,
		arg.Key,
		arg.Name,
		arg.MimeType,
		arg.Size,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Bucket,
		&i.Key,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPDFJob = `-- name: CreatePDFJob :one
INSERT INTO pdf_jobs (
    tenant_id, template_code, payload, status
) VALUES (
    $1, $2, $3, 'pending'
) RETURNING id, tenant_id, template_code, payload, status, file_id, error_message, created_at, updated_at
`

type CreatePDFJobParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	TemplateCode string      `json:"template_code"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) CreatePDFJob(ctx context.Context, arg CreatePDFJobParams) (PdfJob, error) {
	row := q.db.QueryRow(ctx, createPDFJob, arg.TenantID, arg.TemplateCode, arg.Payload)
	var i PdfJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateCode,
		&i.Payload,
		&i.Status,
		&i.FileID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, tenant_id, bucket, key, name, mime_type, size, url, uploaded_by, created_at, updated_at FROM files 
WHERE id = $1 AND tenant_id = $2
`

type GetFileParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRow(ctx, getFile, arg.ID, arg.TenantID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Bucket,
		&i.Key,
		&i.Name,
		&i.MimeType,
		&i.Size,
		&i.Url,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPDFTemplate = `-- name: GetPDFTemplate :one
SELECT id, tenant_id, code, name, html_body, version, is_active, created_at FROM pdf_templates
WHERE tenant_id = $1 AND code = $2 AND is_active = true
ORDER BY version DESC
LIMIT 1
`

type GetPDFTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetPDFTemplate(ctx context.Context, arg GetPDFTemplateParams) (PdfTemplate, error) {
	row := q.db.QueryRow(ctx, getPDFTemplate, arg.TenantID, arg.Code)
	var i PdfTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.HtmlBody,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updatePDFJobStatus = `-- name: UpdatePDFJobStatus :one
UPDATE pdf_jobs
SET status = $3, file_id = $4, error_message = $5, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, template_code, payload, status, file_id, error_message, created_at, updated_at
`

type UpdatePDFJobStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Status       pgtype.Text `json:"status"`
	FileID       pgtype.UUID `json:"file_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdatePDFJobStatus(ctx context.Context, arg UpdatePDFJobStatusParams) (PdfJob, error) {
	row := q.db.QueryRow(ctx, updatePDFJobStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.FileID,
		arg.ErrorMessage,
	)
	var i PdfJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TemplateCode,
		&i.Payload,
		&i.Status,
		&i.FileID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
