// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holidays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHoliday = `-- name: CreateHoliday :one
INSERT INTO holidays (
    tenant_id, name, holiday_date, holiday_type
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, name, holiday_date, holiday_type, created_at
`

type CreateHolidayParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	HolidayDate pgtype.Date `json:"holiday_date"`
	HolidayType string      `json:"holiday_type"`
}

func (q *Queries) CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, createHoliday,
		arg.TenantID,
		arg.Name,
		arg.HolidayDate,
		arg.HolidayType,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HolidayDate,
		&i.HolidayType,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM holidays WHERE id = $1 AND tenant_id = $2
`

type DeleteHolidayParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteHoliday(ctx context.Context, arg DeleteHolidayParams) error {
	_, err := q.db.Exec(ctx, deleteHoliday, arg.ID, arg.TenantID)
	return err
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, tenant_id, name, holiday_date, holiday_type, created_at FROM holidays
WHERE tenant_id = $1 AND holiday_date >= $2 AND holiday_date <= $3
ORDER BY holiday_date ASC
`

type ListHolidaysParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	HolidayDate   pgtype.Date `json:"holiday_date"`
	HolidayDate_2 pgtype.Date `json:"holiday_date_2"`
}

func (q *Queries) ListHolidays(ctx context.Context, arg ListHolidaysParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidays, arg.TenantID, arg.HolidayDate, arg.HolidayDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.HolidayDate,
			&i.HolidayType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
