// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ApprovalRequest struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	Module      string             `json:"module"`
	Action      string             `json:"action"`
	ResourceID  pgtype.UUID        `json:"resource_id"`
	Payload     []byte             `json:"payload"`
	Status      pgtype.Text        `json:"status"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceEntry struct {
	SessionID pgtype.UUID        `json:"session_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	Status    string             `json:"status"`
	Remarks   pgtype.Text        `json:"remarks"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AttendanceSession struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ClassSectionID pgtype.UUID        `json:"class_section_id"`
	Date           pgtype.Date        `json:"date"`
	MarkedBy       pgtype.UUID        `json:"marked_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RequestID    pgtype.Text        `json:"request_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	BeforeState  []byte             `json:"before_state"`
	AfterState   []byte             `json:"after_state"`
	ReasonCode   pgtype.Text        `json:"reason_code"`
	IpAddress    pgtype.Text        `json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AvailabilityException struct {
	ID              pgtype.UUID `json:"id"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	ExceptionDate   pgtype.Date `json:"exception_date"`
	IsUnavailable   pgtype.Bool `json:"is_unavailable"`
	CustomStartTime pgtype.Time `json:"custom_start_time"`
	CustomEndTime   pgtype.Time `json:"custom_end_time"`
	Note            pgtype.Text `json:"note"`
}

type AvailabilityRule struct {
	ID                  pgtype.UUID `json:"id"`
	OwnerUserID         pgtype.UUID `json:"owner_user_id"`
	Timezone            pgtype.Text `json:"timezone"`
	DayOfWeek           int32       `json:"day_of_week"`
	StartTime           pgtype.Time `json:"start_time"`
	EndTime             pgtype.Time `json:"end_time"`
	SlotIntervalMinutes pgtype.Int4 `json:"slot_interval_minutes"`
	BufferBeforeMinutes pgtype.Int4 `json:"buffer_before_minutes"`
	BufferAfterMinutes  pgtype.Int4 `json:"buffer_after_minutes"`
	MaxBookingsPerSlot  pgtype.Int4 `json:"max_bookings_per_slot"`
	IsActive            pgtype.Bool `json:"is_active"`
}

type BookingEvent struct {
	ID          pgtype.UUID        `json:"id"`
	BookingID   pgtype.UUID        `json:"booking_id"`
	EventType   string             `json:"event_type"`
	PayloadJson []byte             `json:"payload_json"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Branch struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	Address   pgtype.Text        `json:"address"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CalendarConnection struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Provider    string             `json:"provider"`
	Status      pgtype.Text        `json:"status"`
	Scopes      []string           `json:"scopes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Level     pgtype.Int4        `json:"level"`
	Stream    pgtype.Text        `json:"stream"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DemoBooking struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	DemoTypeID        pgtype.UUID        `json:"demo_type_id"`
	StartAtUtc        pgtype.Timestamptz `json:"start_at_utc"`
	EndAtUtc          pgtype.Timestamptz `json:"end_at_utc"`
	Timezone          string             `json:"timezone"`
	Status            string             `json:"status"`
	Name              string             `json:"name"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	SchoolName        string             `json:"school_name"`
	City              pgtype.Text        `json:"city"`
	StudentCountRange pgtype.Text        `json:"student_count_range"`
	Message           pgtype.Text        `json:"message"`
	SourcePage        pgtype.Text        `json:"source_page"`
	UtmSource         pgtype.Text        `json:"utm_source"`
	UtmCampaign       pgtype.Text        `json:"utm_campaign"`
	UtmMedium         pgtype.Text        `json:"utm_medium"`
	ConfirmationToken string             `json:"confirmation_token"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	RequestIp         pgtype.Text        `json:"request_ip"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DemoType struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	DurationMinutes int32              `json:"duration_minutes"`
	Description     pgtype.Text        `json:"description"`
	IsActive        pgtype.Bool        `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Exam struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	Name           string             `json:"name"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	Status         pgtype.Text        `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ExamSubject struct {
	ExamID    pgtype.UUID `json:"exam_id"`
	SubjectID pgtype.UUID `json:"subject_id"`
	MaxMarks  int32       `json:"max_marks"`
	ExamDate  pgtype.Date `json:"exam_date"`
}

type FeeHead struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Type      pgtype.Text        `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FeePlan struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Name           string             `json:"name"`
	AcademicYearID pgtype.UUID        `json:"academic_year_id"`
	TotalAmount    pgtype.Int8        `json:"total_amount"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type FeePlanItem struct {
	PlanID  pgtype.UUID `json:"plan_id"`
	HeadID  pgtype.UUID `json:"head_id"`
	Amount  int64       `json:"amount"`
	DueDate pgtype.Date `json:"due_date"`
	Info    pgtype.Text `json:"info"`
}

type FeeRefund struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ReceiptID pgtype.UUID        `json:"receipt_id"`
	Amount    int64              `json:"amount"`
	Reason    pgtype.Text        `json:"reason"`
	Status    pgtype.Text        `json:"status"`
	DecidedBy pgtype.UUID        `json:"decided_by"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Bucket     string             `json:"bucket"`
	Key        string             `json:"key"`
	Name       string             `json:"name"`
	MimeType   pgtype.Text        `json:"mime_type"`
	Size       pgtype.Int8        `json:"size"`
	Url        pgtype.Text        `json:"url"`
	UploadedBy pgtype.UUID        `json:"uploaded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Guardian struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	FullName  string             `json:"full_name"`
	Phone     string             `json:"phone"`
	Email     pgtype.Text        `json:"email"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type Integration struct {
	ID               pgtype.UUID        `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	Category         string             `json:"category"`
	ShortDescription pgtype.Text        `json:"short_description"`
	LongDescription  pgtype.Text        `json:"long_description"`
	LogoUrl          pgtype.Text        `json:"logo_url"`
	WebsiteUrl       pgtype.Text        `json:"website_url"`
	Status           pgtype.Text        `json:"status"`
	Locale           string             `json:"locale"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Lead struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Phone        string             `json:"phone"`
	Email        string             `json:"email"`
	SchoolName   string             `json:"school_name"`
	City         pgtype.Text        `json:"city"`
	StudentCount pgtype.Int4        `json:"student_count"`
	Message      pgtype.Text        `json:"message"`
	SourcePage   pgtype.Text        `json:"source_page"`
	UtmCampaign  pgtype.Text        `json:"utm_campaign"`
	UtmSource    pgtype.Text        `json:"utm_source"`
	UtmMedium    pgtype.Text        `json:"utm_medium"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LeaveRequest struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	FromDate  pgtype.Date        `json:"from_date"`
	ToDate    pgtype.Date        `json:"to_date"`
	Reason    pgtype.Text        `json:"reason"`
	Status    pgtype.Text        `json:"status"`
	DecidedBy pgtype.UUID        `json:"decided_by"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Lock struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Module     string             `json:"module"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	LockedBy   pgtype.UUID        `json:"locked_by"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MarketingPdfJob struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Locale    string             `json:"locale"`
	Status    pgtype.Text        `json:"status"`
	FileID    pgtype.UUID        `json:"file_id"`
	RequestIp pgtype.Text        `json:"request_ip"`
	Error     pgtype.Text        `json:"error"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MarksEntry struct {
	ExamID        pgtype.UUID        `json:"exam_id"`
	SubjectID     pgtype.UUID        `json:"subject_id"`
	StudentID     pgtype.UUID        `json:"student_id"`
	MarksObtained pgtype.Numeric     `json:"marks_obtained"`
	Remarks       pgtype.Text        `json:"remarks"`
	EnteredBy     pgtype.UUID        `json:"entered_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Notice struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Scope     []byte             `json:"scope"`
	PublishAt pgtype.Timestamptz `json:"publish_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type NoticeAck struct {
	NoticeID pgtype.UUID        `json:"notice_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	AckAt    pgtype.Timestamptz `json:"ack_at"`
}

type NotificationTemplate struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Channel   string             `json:"channel"`
	Locale    string             `json:"locale"`
	Subject   pgtype.Text        `json:"subject"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID           int64              `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	RequestID    pgtype.Text        `json:"request_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	Status       pgtype.Text        `json:"status"`
	Attempts     pgtype.Int4        `json:"attempts"`
	LastError    pgtype.Text        `json:"last_error"`
	ProcessAfter pgtype.Timestamptz `json:"process_after"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PartnerApplication struct {
	ID          pgtype.UUID        `json:"id"`
	CompanyName string             `json:"company_name"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Website     pgtype.Text        `json:"website"`
	Category    string             `json:"category"`
	Description pgtype.Text        `json:"description"`
	LogoFileID  pgtype.UUID        `json:"logo_file_id"`
	Status      pgtype.Text        `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PaymentOrder struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	StudentID   pgtype.UUID        `json:"student_id"`
	Amount      int64              `json:"amount"`
	Mode        string             `json:"mode"`
	Status      pgtype.Text        `json:"status"`
	ExternalRef pgtype.Text        `json:"external_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PdfJob struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	TemplateCode string             `json:"template_code"`
	Payload      []byte             `json:"payload"`
	Status       pgtype.Text        `json:"status"`
	FileID       pgtype.UUID        `json:"file_id"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PdfTemplate struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	HtmlBody  string             `json:"html_body"`
	Version   pgtype.Int4        `json:"version"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Module      string             `json:"module"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Policy struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Module    string             `json:"module"`
	Action    string             `json:"action"`
	Logic     []byte             `json:"logic"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Receipt struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ReceiptNumber      string             `json:"receipt_number"`
	StudentID          pgtype.UUID        `json:"student_id"`
	AmountPaid         int64              `json:"amount_paid"`
	PaymentMode        string             `json:"payment_mode"`
	Status             pgtype.Text        `json:"status"`
	CancelledBy        pgtype.UUID        `json:"cancelled_by"`
	CancellationReason pgtype.Text        `json:"cancellation_reason"`
	TransactionRef     pgtype.Text        `json:"transaction_ref"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SeriesID           pgtype.UUID        `json:"series_id"`
}

type ReceiptSeries struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	BranchID      pgtype.UUID        `json:"branch_id"`
	Prefix        string             `json:"prefix"`
	CurrentNumber pgtype.Int4        `json:"current_number"`
	IsActive      pgtype.Bool        `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Review struct {
	ID         pgtype.UUID        `json:"id"`
	Token      pgtype.Text        `json:"token"`
	Rating     pgtype.Int4        `json:"rating"`
	Content    string             `json:"content"`
	Name       string             `json:"name"`
	Role       string             `json:"role"`
	SchoolName string             `json:"school_name"`
	City       pgtype.Text        `json:"city"`
	LogoFileID pgtype.UUID        `json:"logo_file_id"`
	Status     pgtype.Text        `json:"status"`
	Consent    pgtype.Bool        `json:"consent"`
	IsFeatured pgtype.Bool        `json:"is_featured"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ReviewRequest struct {
	ID           pgtype.UUID        `json:"id"`
	Token        string             `json:"token"`
	SchoolName   string             `json:"school_name"`
	ContactEmail string             `json:"contact_email"`
	Locale       pgtype.Text        `json:"locale"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Status       pgtype.Text        `json:"status"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	IsSystem    pgtype.Bool        `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RoleAssignment struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	ScopeType string             `json:"scope_type"`
	ScopeID   pgtype.UUID        `json:"scope_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type Section struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ClassID   pgtype.UUID        `json:"class_id"`
	Name      string             `json:"name"`
	Capacity  pgtype.Int4        `json:"capacity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo []byte             `json:"device_info"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Student struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	BranchID        pgtype.UUID        `json:"branch_id"`
	AdmissionNumber string             `json:"admission_number"`
	RollNumber      pgtype.Text        `json:"roll_number"`
	FullName        string             `json:"full_name"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	Gender          pgtype.Text        `json:"gender"`
	Address         pgtype.Text        `json:"address"`
	SectionID       pgtype.UUID        `json:"section_id"`
	Status          pgtype.Text        `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type StudentDocument struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	FileID    pgtype.UUID        `json:"file_id"`
	Type      string             `json:"type"`
	Note      pgtype.Text        `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StudentFeePlan struct {
	StudentID  pgtype.UUID        `json:"student_id"`
	PlanID     pgtype.UUID        `json:"plan_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

type StudentGuardian struct {
	StudentID    pgtype.UUID `json:"student_id"`
	GuardianID   pgtype.UUID `json:"guardian_id"`
	Relationship string      `json:"relationship"`
	IsPrimary    pgtype.Bool `json:"is_primary"`
}

type Subject struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Code      pgtype.Text        `json:"code"`
	Type      pgtype.Text        `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Subdomain string             `json:"subdomain"`
	Domain    pgtype.Text        `json:"domain"`
	LogoUrl   pgtype.Text        `json:"logo_url"`
	Config    []byte             `json:"config"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	FullName  string             `json:"full_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Provider   string             `json:"provider"`
	Identifier string             `json:"identifier"`
	Credential pgtype.Text        `json:"credential"`
	LastLogin  pgtype.Timestamptz `json:"last_login"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	BalancePaise pgtype.Int8        `json:"balance_paise"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type WalletLedger struct {
	ID          int64              `json:"id"`
	WalletID    pgtype.UUID        `json:"wallet_id"`
	AmountPaise int64              `json:"amount_paise"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	ReferenceID pgtype.Text        `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
