// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationTemplate = `-- name: CreateNotificationTemplate :one
INSERT INTO notification_templates (
    tenant_id, code, channel, locale, subject, body
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, code, channel, locale, subject, body, created_at
`

type CreateNotificationTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
	Channel  string      `json:"channel"`
	Locale   string      `json:"locale"`
	Subject  pgtype.Text `json:"subject"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateNotificationTemplate(ctx context.Context, arg CreateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, createNotificationTemplate,
		arg.TenantID,
		arg.Code,
		arg.Channel,
		arg.Locale,
		arg.Subject,
		arg.Body,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationTemplate = `-- name: DeleteNotificationTemplate :exec
DELETE FROM notification_templates
WHERE id = $1 AND tenant_id = $2
`

type DeleteNotificationTemplateParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteNotificationTemplate(ctx context.Context, arg DeleteNotificationTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationTemplate, arg.ID, arg.TenantID)
	return err
}

const getNotificationTemplate = `-- name: GetNotificationTemplate :one
SELECT id, tenant_id, code, channel, locale, subject, body, created_at FROM notification_templates
WHERE id = $1 AND (tenant_id = $2 OR tenant_id IS NULL)
`

type GetNotificationTemplateParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetNotificationTemplate(ctx context.Context, arg GetNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getNotificationTemplate, arg.ID, arg.TenantID)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationTemplates = `-- name: ListNotificationTemplates :many
SELECT id, tenant_id, code, channel, locale, subject, body, created_at FROM notification_templates
WHERE (tenant_id = $1 OR tenant_id IS NULL)
ORDER BY code ASC, channel ASC
`

func (q *Queries) ListNotificationTemplates(ctx context.Context, tenantID pgtype.UUID) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listNotificationTemplates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationTemplate
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Channel,
			&i.Locale,
			&i.Subject,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveNotificationTemplate = `-- name: ResolveNotificationTemplate :one
SELECT id, tenant_id, code, channel, locale, subject, body, created_at FROM notification_templates
WHERE (tenant_id = $1 OR tenant_id IS NULL)
AND code = $2
AND channel = $3
ORDER BY (CASE WHEN locale = $4 THEN 0 WHEN locale = 'en' THEN 1 ELSE 2 END) ASC
LIMIT 1
`

type ResolveNotificationTemplateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
	Channel  string      `json:"channel"`
	Locale   string      `json:"locale"`
}

func (q *Queries) ResolveNotificationTemplate(ctx context.Context, arg ResolveNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, resolveNotificationTemplate,
		arg.TenantID,
		arg.Code,
		arg.Channel,
		arg.Locale,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const updateNotificationTemplate = `-- name: UpdateNotificationTemplate :one
UPDATE notification_templates
SET 
    subject = $3,
    body = $4,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, code, channel, locale, subject, body, created_at
`

type UpdateNotificationTemplateParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Subject  pgtype.Text `json:"subject"`
	Body     string      `json:"body"`
}

func (q *Queries) UpdateNotificationTemplate(ctx context.Context, arg UpdateNotificationTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, updateNotificationTemplate,
		arg.ID,
		arg.TenantID,
		arg.Subject,
		arg.Body,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Channel,
		&i.Locale,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}
