// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: student_notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConfidentialNote = `-- name: CreateConfidentialNote :one
INSERT INTO student_confidential_notes (
    tenant_id, student_id, created_by, encrypted_content
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, student_id, created_by, encrypted_content, created_at, updated_at
`

type CreateConfidentialNoteParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	StudentID        pgtype.UUID `json:"student_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	EncryptedContent string      `json:"encrypted_content"`
}

func (q *Queries) CreateConfidentialNote(ctx context.Context, arg CreateConfidentialNoteParams) (StudentConfidentialNote, error) {
	row := q.db.QueryRow(ctx, createConfidentialNote,
		arg.TenantID,
		arg.StudentID,
		arg.CreatedBy,
		arg.EncryptedContent,
	)
	var i StudentConfidentialNote
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StudentID,
		&i.CreatedBy,
		&i.EncryptedContent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfidentialNote = `-- name: DeleteConfidentialNote :exec
DELETE FROM student_confidential_notes WHERE id = $1 AND tenant_id = $2
`

type DeleteConfidentialNoteParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteConfidentialNote(ctx context.Context, arg DeleteConfidentialNoteParams) error {
	_, err := q.db.Exec(ctx, deleteConfidentialNote, arg.ID, arg.TenantID)
	return err
}

const listConfidentialNotes = `-- name: ListConfidentialNotes :many
SELECT id, tenant_id, student_id, created_by, encrypted_content, created_at, updated_at FROM student_confidential_notes
WHERE tenant_id = $1 AND student_id = $2
ORDER BY created_at DESC
`

type ListConfidentialNotesParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) ListConfidentialNotes(ctx context.Context, arg ListConfidentialNotesParams) ([]StudentConfidentialNote, error) {
	rows, err := q.db.Query(ctx, listConfidentialNotes, arg.TenantID, arg.StudentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentConfidentialNote
	for rows.Next() {
		var i StudentConfidentialNote
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StudentID,
			&i.CreatedBy,
			&i.EncryptedContent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
