// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, name, subdomain, domain, config, board_type, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, subdomain, domain, logo_url, board_type, config, is_active, created_at, updated_at
`

type CreateTenantParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Subdomain string      `json:"subdomain"`
	Domain    pgtype.Text `json:"domain"`
	Config    []byte      `json:"config"`
	BoardType pgtype.Text `json:"board_type"`
	IsActive  pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Subdomain,
		arg.Domain,
		arg.Config,
		arg.BoardType,
		arg.IsActive,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Domain,
		&i.LogoUrl,
		&i.BoardType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, subdomain, domain, logo_url, board_type, config, is_active, created_at, updated_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Domain,
		&i.LogoUrl,
		&i.BoardType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySubdomain = `-- name: GetTenantBySubdomain :one
SELECT id, name, subdomain, domain, logo_url, board_type, config, is_active, created_at, updated_at FROM tenants
WHERE subdomain = $1 LIMIT 1
`

func (q *Queries) GetTenantBySubdomain(ctx context.Context, subdomain string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySubdomain, subdomain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Domain,
		&i.LogoUrl,
		&i.BoardType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantBoardType = `-- name: UpdateTenantBoardType :one
UPDATE tenants
SET board_type = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, subdomain, domain, logo_url, board_type, config, is_active, created_at, updated_at
`

type UpdateTenantBoardTypeParams struct {
	ID        pgtype.UUID `json:"id"`
	BoardType pgtype.Text `json:"board_type"`
}

func (q *Queries) UpdateTenantBoardType(ctx context.Context, arg UpdateTenantBoardTypeParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantBoardType, arg.ID, arg.BoardType)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Domain,
		&i.LogoUrl,
		&i.BoardType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantConfig = `-- name: UpdateTenantConfig :one
UPDATE tenants
SET config = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, subdomain, domain, logo_url, board_type, config, is_active, created_at, updated_at
`

type UpdateTenantConfigParams struct {
	ID     pgtype.UUID `json:"id"`
	Config []byte      `json:"config"`
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantConfig, arg.ID, arg.Config)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Domain,
		&i.LogoUrl,
		&i.BoardType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
