import { test, expect } from '@playwright/test';

test.describe('Notices & Circulars Smoke Tests', () => {
  test('Admin can publish a notice', async ({ page }) => {
    await page.goto('/admin/notices');
    await expect(page.getByText('Notices & Circulars')).toBeVisible();

    await page.getByPlaceholder('e.g. Annual Day Notice').fill('Playwright Test Notice');
    await page.getByPlaceholder('Type your message here...').fill('This is a test notice message generated by Playwright.');

    await page.getByRole('button', { name: 'Publish Notice' }).click();

    // Check if added to list
    await expect(page.getByText('Playwright Test Notice')).toBeVisible();
  });

  test('Parent can view and acknowledge a notice', async ({ page }) => {
    await page.goto('/parent/notices');
    await expect(page.getByText('Notices & Communications')).toBeVisible();

    const unreadNotice = page.getByText('School Annual Day Celebration');
    await expect(unreadNotice).toBeVisible();

    const ackButton = page.getByRole('button', { name: 'Acknowledge' });
    await ackButton.click();

    // Check if status changed to Acknowledged
    await expect(page.getByText('Acknowledged')).toBeVisible();
  });
});
