package sis

import (
	"bytes"
	"context"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

func (s *Student360Service) GetStudentPortfolioPDF(ctx context.Context, tenantID, studentID string) ([]byte, error) {
	data, err := s.GetStudent360(ctx, tenantID, studentID)
	if err != nil {
		return nil, err
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Styling
	primaryColor := struct{ r, g, b int }{30, 41, 59} // Slate 800
	accentColor := struct{ r, g, b int }{79, 70, 229} // Indigo 600

	// Header
	pdf.SetFillColor(primaryColor.r, primaryColor.g, primaryColor.b)
	pdf.Rect(0, 0, 210, 45, "F")

	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Arial", "B", 24)
	pdf.CellFormat(0, 20, "STUDENT 360° PORTFOLIO", "", 1, "C", false, 0, "")
	
	pdf.SetFont("Arial", "B", 10)
	pdf.CellFormat(0, 5, "Official Academic & Behavioral Record", "", 1, "C", false, 0, "")

	pdf.Ln(20)

	// Profiles Section
	pdf.SetTextColor(primaryColor.r, primaryColor.g, primaryColor.b)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 10, "1. Basic Profile")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 11)
	pdf.SetFillColor(248, 250, 252)
	pdf.CellFormat(40, 10, "Full Name:", "B", 0, "L", true, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("%v", data.Profile["full_name"]), "B", 1, "L", false, 0, "")
	pdf.CellFormat(40, 10, "Admission No:", "B", 0, "L", true, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("%v", data.Profile["admission_number"]), "B", 1, "L", false, 0, "")
	pdf.CellFormat(40, 10, "Class & Section:", "B", 0, "L", true, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("%v %v", data.Profile["class"], data.Profile["section"]), "B", 1, "L", false, 0, "")
	pdf.CellFormat(40, 10, "Gender:", "B", 0, "L", true, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("%v", data.Profile["gender"]), "B", 1, "L", false, 0, "")

	pdf.Ln(10)

	// Academics Section
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 10, "2. Academic Overview")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(60, 10, "Attendance Percentage:", "1", 0, "L", false, 0, "")
	pdf.SetTextColor(accentColor.r, accentColor.g, accentColor.b)
	pdf.CellFormat(0, 10, fmt.Sprintf("%.2f%%", data.Academics["attendance_percentage"]), "1", 1, "L", false, 0, "")
	
	pdf.SetTextColor(primaryColor.r, primaryColor.g, primaryColor.b)
	pdf.CellFormat(60, 10, "Latest Exam Average:", "1", 0, "L", false, 0, "")
	pdf.SetTextColor(accentColor.r, accentColor.g, accentColor.b)
	pdf.CellFormat(0, 10, fmt.Sprintf("%.2f%%", data.Academics["latest_exam_avg"]), "1", 1, "L", false, 0, "")

	pdf.Ln(10)

	// Behavior Section
	pdf.SetTextColor(primaryColor.r, primaryColor.g, primaryColor.b)
	pdf.SetFont("Arial", "B", 14)
	pdf.Cell(0, 10, "3. Behavioral Standing")
	pdf.Ln(10)

	points := 0
	for _, log := range data.Behavior {
		if log.Type == "merit" {
			points += log.Points
		} else if log.Type == "demerit" {
			points -= log.Points
		}
	}

	pdf.SetFont("Arial", "B", 11)
	pdf.Cell(0, 8, fmt.Sprintf("Net Merit Points: %d", points))
	pdf.Ln(10)
	
	// List recent behavior logs
	pdf.SetFont("Arial", "B", 10)
	pdf.SetFillColor(241, 245, 249)
	pdf.CellFormat(30, 8, "Date", "1", 0, "C", true, 0, "")
	pdf.CellFormat(30, 8, "Type", "1", 0, "C", true, 0, "")
	pdf.CellFormat(20, 8, "Pts", "1", 0, "C", true, 0, "")
	pdf.CellFormat(0, 8, "Remarks", "1", 1, "C", true, 0, "")

	pdf.SetFont("Arial", "", 9)
	for i, log := range data.Behavior {
		if i >= 10 { break } 
		pdf.CellFormat(30, 8, log.IncidentDate.Format("02-Jan-06"), "1", 0, "C", false, 0, "")
		pdf.CellFormat(30, 8, log.Type, "1", 0, "C", false, 0, "")
		pdf.CellFormat(20, 8, fmt.Sprintf("%d", log.Points), "1", 0, "C", false, 0, "")
		pdf.CellFormat(0, 8, log.Remarks, "1", 1, "L", false, 0, "")
	}

	// Health Section
	if data.Health != nil {
		pdf.Ln(15)
		pdf.SetTextColor(primaryColor.r, primaryColor.g, primaryColor.b)
		pdf.SetFont("Arial", "B", 14)
		pdf.Cell(0, 10, "4. Health Profile")
		pdf.Ln(10)

		pdf.SetFont("Arial", "", 11)
		pdf.CellFormat(40, 10, "Blood Group:", "B", 0, "L", true, 0, "")
		pdf.CellFormat(0, 10, data.Health.BloodGroup, "B", 1, "L", false, 0, "")
		pdf.CellFormat(40, 10, "Medical Conditions:", "B", 0, "L", true, 0, "")
		pdf.CellFormat(0, 10, data.Health.MedicalConditions, "B", 1, "L", false, 0, "")
	}

	// Footer
	pdf.SetY(-30)
	pdf.SetFont("Arial", "I", 8)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(0, 10, "Generated by SchoolERP Automated Reporting Engine", "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("Page %d | Date: %s", pdf.PageNo(), time.Now().Format(time.RFC822)), "", 0, "C", false, 0, "")

	var buf bytes.Buffer
	err = pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
