// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO school_group_members (group_id, tenant_id)
VALUES ($1, $2)
`

type AddGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.TenantID)
	return err
}

const createSchoolGroup = `-- name: CreateSchoolGroup :one
INSERT INTO school_groups (name, description, owner_user_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, owner_user_id, created_at, updated_at
`

type CreateSchoolGroupParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) CreateSchoolGroup(ctx context.Context, arg CreateSchoolGroupParams) (SchoolGroup, error) {
	row := q.db.QueryRow(ctx, createSchoolGroup, arg.Name, arg.Description, arg.OwnerUserID)
	var i SchoolGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupAnalytics = `-- name: GetGroupAnalytics :one
SELECT 
    COUNT(DISTINCT s.id) as total_students,
    COUNT(DISTINCT e.id) as total_employees
FROM school_group_members gm
LEFT JOIN students s ON s.tenant_id = gm.tenant_id
LEFT JOIN employees e ON e.tenant_id = gm.tenant_id
WHERE gm.group_id = $1
`

type GetGroupAnalyticsRow struct {
	TotalStudents  int64 `json:"total_students"`
	TotalEmployees int64 `json:"total_employees"`
}

func (q *Queries) GetGroupAnalytics(ctx context.Context, groupID pgtype.UUID) (GetGroupAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getGroupAnalytics, groupID)
	var i GetGroupAnalyticsRow
	err := row.Scan(&i.TotalStudents, &i.TotalEmployees)
	return i, err
}

const getSchoolGroup = `-- name: GetSchoolGroup :one
SELECT id, name, description, owner_user_id, created_at, updated_at FROM school_groups WHERE id = $1
`

func (q *Queries) GetSchoolGroup(ctx context.Context, id pgtype.UUID) (SchoolGroup, error) {
	row := q.db.QueryRow(ctx, getSchoolGroup, id)
	var i SchoolGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT 
    gm.group_id, gm.tenant_id, gm.added_at,
    t.name as tenant_name
FROM school_group_members gm
JOIN tenants t ON gm.tenant_id = t.id
WHERE gm.group_id = $1
`

type ListGroupMembersRow struct {
	GroupID    pgtype.UUID        `json:"group_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	AddedAt    pgtype.Timestamptz `json:"added_at"`
	TenantName string             `json:"tenant_name"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.TenantID,
			&i.AddedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolGroups = `-- name: ListSchoolGroups :many
SELECT id, name, description, owner_user_id, created_at, updated_at FROM school_groups
WHERE owner_user_id = $1
ORDER BY name
`

func (q *Queries) ListSchoolGroups(ctx context.Context, ownerUserID pgtype.UUID) ([]SchoolGroup, error) {
	rows, err := q.db.Query(ctx, listSchoolGroups, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchoolGroup
	for rows.Next() {
		var i SchoolGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM school_group_members
WHERE group_id = $1 AND tenant_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.TenantID)
	return err
}
