// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quota.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployees = `-- name: CountEmployees :one

SELECT COUNT(*)
FROM employees
WHERE tenant_id = $1
  AND status = 'active'
`

// Quota & Limits
func (q *Queries) CountEmployees(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEffectiveTenantLimit = `-- name: GetEffectiveTenantLimit :one
SELECT COALESCE(
	CASE
		WHEN COALESCE(ts.overrides->'limits'->>@quota_key, '') ~ '^[0-9]+$'
		     AND (
				COALESCE(ts.overrides->'limit_overrides_meta'->@quota_key->>'expires_at', '') = ''
				OR (ts.overrides->'limit_overrides_meta'->@quota_key->>'expires_at')::timestamptz >= NOW()
			 )
		THEN (ts.overrides->'limits'->>@quota_key)::BIGINT
	END,
	CASE
		WHEN COALESCE(pp.limits->>@quota_key, '') ~ '^[0-9]+$'
		THEN (pp.limits->>@quota_key)::BIGINT
	END,
	CASE
		WHEN $1 = 'students' THEN 500::BIGINT
		WHEN $1 = 'staff' THEN 100::BIGINT
		WHEN $1 = 'storage_mb' THEN 10240::BIGINT
		ELSE 0::BIGINT
	END
)::BIGINT AS effective_limit
FROM tenants t
LEFT JOIN tenant_subscriptions ts ON ts.tenant_id = t.id
LEFT JOIN platform_plans pp ON pp.id = ts.plan_id
WHERE t.id = $2
LIMIT 1
`

type GetEffectiveTenantLimitParams struct {
	QuotaKey interface{} `json:"quota_key"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetEffectiveTenantLimit(ctx context.Context, arg GetEffectiveTenantLimitParams) (int64, error) {
	row := q.db.QueryRow(ctx, getEffectiveTenantLimit, arg.QuotaKey, arg.TenantID)
	var effective_limit int64
	err := row.Scan(&effective_limit)
	return effective_limit, err
}

const getTenantStorageUsage = `-- name: GetTenantStorageUsage :one
SELECT COALESCE(SUM(COALESCE(size, 0)), 0)::BIGINT
FROM files
WHERE tenant_id = $1
`

func (q *Queries) GetTenantStorageUsage(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTenantStorageUsage, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
