-- 000010_foundation_updates.up.sql

ALTER TABLE policies ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE approval_requests ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE locks ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
